version: 2

project_name: tj

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/tj
    binary: tj
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums_darwin.txt"

changelog:
  disable: true

release:
  mode: append
