package cmd

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"tj/internal/config"
)

type initAnswers struct {
	Sound          bool
	Notify         bool
	LayoutColumns  bool
	SortByActivity bool
}

var configTemplate = template.Must(template.New("config").Parse(`# Teejay Configuration
# Generated by 'tj init' — edit freely
# For advanced options, see: tj --help

# Alert settings
alerts:
  # Play terminal bell when a pane becomes ready
  sound_on_ready: {{ .Sound }}

  # Send desktop notification when a pane becomes ready
  notify_on_ready: {{ .Notify }}

# Display settings
display:
  # Layout: "default" (list + preview) or "columns" (multi-column grid)
  layout_mode: "{{ if .LayoutColumns }}columns{{ else }}default{{ end }}"

  # Sort order: false = watchlist order, true = activity sort
  sort_by_activity: {{ .SortByActivity }}

  # Color gradient on waiting indicators (bright = just finished)
  recency_color: true

  # Show pane preview panel
  show_preview: true
`))

// InitConfig runs the interactive init wizard and writes a config file.
func InitConfig() error {
	cfgPath, err := config.ConfigPath()
	if err != nil {
		return fmt.Errorf("cannot determine config path: %w", err)
	}

	reader := bufio.NewReader(Stdin)

	// Check for existing config
	if _, err := os.Stat(cfgPath); err == nil {
		action, err := promptChoice(reader,
			fmt.Sprintf("Config file already exists at %s.\nWhat would you like to do?", cfgPath),
			[]string{"overwrite", "backup", "cancel"},
		)
		if err != nil {
			return err
		}
		switch action {
		case "cancel":
			fmt.Println("No changes made.")
			return nil
		case "backup":
			bakPath := cfgPath + ".bak"
			if err := os.Rename(cfgPath, bakPath); err != nil {
				return fmt.Errorf("failed to backup config: %w", err)
			}
			fmt.Printf("Backed up existing config to %s\n", bakPath)
		case "overwrite":
			// proceed
		}
	}

	fmt.Println("\nWelcome to teejay! Let's set up your config.")

	answers := initAnswers{}

	answers.Sound, err = promptYesNo(reader, "Enable sound alerts when a pane becomes ready?", false)
	if err != nil {
		return err
	}

	answers.Notify, err = promptYesNo(reader, "Enable desktop notifications when a pane becomes ready?", false)
	if err != nil {
		return err
	}

	layout, err := promptChoice(reader, "Default layout?", []string{"single-column (default)", "multi-column"})
	if err != nil {
		return err
	}
	answers.LayoutColumns = (layout == "multi-column")

	sortOrder, err := promptChoice(reader, "Default sort order?", []string{"watchlist order (default)", "activity (busy first)"})
	if err != nil {
		return err
	}
	answers.SortByActivity = (sortOrder == "activity (busy first)")

	// Create parent directories
	dir := filepath.Dir(cfgPath)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}

	// Write config file
	f, err := os.Create(cfgPath)
	if err != nil {
		return fmt.Errorf("failed to create config file: %w", err)
	}
	defer f.Close()

	if err := configTemplate.Execute(f, answers); err != nil {
		return fmt.Errorf("failed to write config: %w", err)
	}

	fmt.Printf("\nConfig written to %s\n", cfgPath)
	return nil
}

// promptYesNo asks a yes/no question with a default value.
func promptYesNo(reader *bufio.Reader, question string, defaultVal bool) (bool, error) {
	defStr := "y/N"
	if defaultVal {
		defStr = "Y/n"
	}
	fmt.Printf("%s [%s]: ", question, defStr)

	input, err := reader.ReadString('\n')
	if err != nil {
		return defaultVal, nil
	}
	input = strings.TrimSpace(strings.ToLower(input))

	if input == "" {
		return defaultVal, nil
	}
	switch input {
	case "y", "yes":
		return true, nil
	case "n", "no":
		return false, nil
	default:
		return defaultVal, nil
	}
}

// promptChoice asks the user to pick from numbered options.
func promptChoice(reader *bufio.Reader, question string, options []string) (string, error) {
	fmt.Println(question)
	for i, opt := range options {
		fmt.Printf("  %d) %s\n", i+1, opt)
	}
	fmt.Printf("Choose [1]: ")

	input, err := reader.ReadString('\n')
	if err != nil {
		return options[0], nil
	}
	input = strings.TrimSpace(input)

	if input == "" {
		return options[0], nil
	}

	for i, opt := range options {
		if input == fmt.Sprintf("%d", i+1) {
			return opt, nil
		}
	}
	return options[0], nil
}
